### ISSUE TITLE
Lassa parameters csv file

### ISSUE THREAD

**Issue by chloerice48** [mrc-ide/epireview#115]
Hi! The lassa parameters csv file (epireview/inst/extdata/Lassa_parameters.csv) appears to be missing the field article_qa_score. Can you please update this file? Thank you!

**Comment by chloerice48** [comment]
Also - just noticed in the lassa_articles.csv file that the article_qa_score is also not populated. Thanks for looking into this!

**Comment by sangeetabhatia03** [comment]
Hi Chloe, We assign a QA score to each article, even where multiple parameters might have been extracted from an article.
We have now included functionality to update QA score on the fly, like so:

```
lassa <- load_epidata("lassa")
articles <- assign_qa_score(lassa$articles)
```

articles is a 2 element list where the first element is the original data, with new columns qa_numerator, qa_denominator, and qa_score.
In our analysis we sometimes found it useful to have this score also attached to the params dataset so that we could for example filter estimates based on the QA score. To achieve this, we join the updated articles data with the params data.
Hope this helps! Let us know if you need more info.

**Comment by chloerice48** [comment]
Ah, thanks Sangeeta! I'll make sure to do this step the next time I am loading the Lassa parameters into the GREP (WHO Collaboratory project which I believe you are very aware of!!) :) Thanks heaps!
